[project]
name = 'stacks-payday'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 4
epoch = 'latest'

[contracts.ddtrvlr-multisig]
path = 'contracts/ddtrvlr-multisig.clar'
clarity_version = 4
epoch = 'latest'

[contracts.ddtrvlr-nft]
path = 'contracts/ddtrvlr-nft.clar'
clarity_version = 4
epoch = 'latest'

[contracts.ddtrvlr-token]
path = 'contracts/ddtrvlr-token.clar'
clarity_version = 4
epoch = 'latest'

[contracts.ddtrvlr-vault]
path = 'contracts/ddtrvlr-vault.clar'
clarity_version = 4
epoch = 'latest'

[contracts.ddtrvlr-voting]
path = 'contracts/ddtrvlr-voting.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lint_groups]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
